---
# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: MarkDown linting
on: [push, pull_request]  # yamllint disable-line rule:truthy
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0

      - name: MarkdownLint
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
        with:
          # allow duplicate subsections, see https://github.com/DavidAnson/markdownlint/blob/main/doc/md024.md
          siblings_only: true
          # all markdown, except filter out {demos,version-specific,easybuild-v5}/* for now, until we fix issues in those sections
          globs: |
            **/*.md
            #docs/demos
            #docs/version-specific
            #docs/easybuild-v5
